//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionPlanTasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectionPlanTasks()
        {
            this.InspectionPlanTaskMitigationColumns = new HashSet<InspectionPlanTaskMitigationColumns>();
        }
    
        public System.Guid InspectionPlanTaskId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid InspectionPlanId { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<System.Guid> RecommendationId { get; set; }
        public int RowIndex { get; set; }
        public string TaskExtent { get; set; }
        public Nullable<double> TaskFrequency { get; set; }
        public string TaskInterval { get; set; }
        public string TaskName { get; set; }
        public string TaskReference { get; set; }
        public string MitigationType { get; set; }
        public int SourceType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.Guid> LastInspectionId { get; set; }
        public bool IsStaticDueDate { get; set; }
        public int FrequencySource { get; set; }
        public string MitigationSource { get; set; }
        public bool OverrideFrequency { get; set; }
        public bool LastInspectionDateOverriden { get; set; }
        public string ErpMaintenancePlanNumber { get; set; }
        public string ErpNotificationNumber { get; set; }
        public string ErpNotificationSystemStatus { get; set; }
        public string ErpWorkOrderNumber { get; set; }
        public string ErpWorkOrderSystemStatus { get; set; }
        public bool SendToErp { get; set; }
        public string ErpNotificationUserStatus { get; set; }
        public string ErpReportedBy { get; set; }
        public string ErpWorkOrderUserStatus { get; set; }
        public Nullable<System.DateTime> HistoricInspectionDate { get; set; }
        public System.Guid MasterInspectionMethodId { get; set; }
        public int LastInspectionDateSource { get; set; }
        public Nullable<System.DateTime> ManualLastInspectionDate { get; set; }
    
        public virtual InspectionPlans InspectionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlanTaskMitigationColumns> InspectionPlanTaskMitigationColumns { get; set; }
    }
}
