//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimModelRunOverallRisk> DimModelRunOverallRisk { get; set; }
        public virtual DbSet<ModelNodeMetadata> ModelNodeMetadata { get; set; }
        public virtual DbSet<NodeInputMetadata> NodeInputMetadata { get; set; }
        public virtual DbSet<NodeOutputMetadata> NodeOutputMetadata { get; set; }
        public virtual DbSet<OrgTreeNodeModelRunInputs> OrgTreeNodeModelRunInputs { get; set; }
        public virtual DbSet<OrgTreeNodeModelRunOutputs> OrgTreeNodeModelRunOutputs { get; set; }
        public virtual DbSet<OrgTreeNodeModelRuns> OrgTreeNodeModelRuns { get; set; }
        public virtual DbSet<OrgTreeNodes> OrgTreeNodes { get; set; }
        public virtual DbSet<RiskMatrixConsequenceVectors> RiskMatrixConsequenceVectors { get; set; }
        public virtual DbSet<RiskMatrixProbabilityVectors> RiskMatrixProbabilityVectors { get; set; }
        public virtual DbSet<RunnableLookupRowDisplayValues> RunnableLookupRowDisplayValues { get; set; }
        public virtual DbSet<RunnableModel> RunnableModel { get; set; }
        public virtual DbSet<ComponentDetails> ComponentDetails { get; set; }
        public virtual DbSet<HierarchyTemplates> HierarchyTemplates { get; set; }
    }
}
