//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelNodeMetadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelNodeMetadata()
        {
            this.NodeInputMetadata = new HashSet<NodeInputMetadata>();
            this.NodeOutputMetadata = new HashSet<NodeOutputMetadata>();
        }
    
        public System.Guid ModelNodeId { get; set; }
        public bool DefaultOutputNode { get; set; }
        public System.Guid ModelId { get; set; }
        public System.Guid NodeId { get; set; }
        public string NodeName { get; set; }
        public int RunOrder { get; set; }
        public string NodeLabel { get; set; }
    
        public virtual RunnableModel RunnableModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodeInputMetadata> NodeInputMetadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodeOutputMetadata> NodeOutputMetadata { get; set; }
    }
}
