//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTreeNodeModelRunInputs
    {
        public System.Guid OrgTreeNodeModelRunInputId { get; set; }
        public System.Guid NodeInputId { get; set; }
        public System.Guid OrgTreeNodeModelRunId { get; set; }
        public string Value { get; set; }
        public string DisplayValue { get; set; }
        public System.Guid ModelNodeId { get; set; }
        public Nullable<System.Guid> DisplayValueUomId { get; set; }
    
        public virtual OrgTreeNodeModelRuns OrgTreeNodeModelRuns { get; set; }
    }
}
