//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTreeNodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgTreeNodes()
        {
            this.OrgTreeNodeModelRuns = new HashSet<OrgTreeNodeModelRuns>();
            this.OrgTreeNodes1 = new HashSet<OrgTreeNodes>();
        }
    
        public System.Guid OrgTreeNodeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public string Discriminator { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string Name { get; set; }
        public int OrgTreeNodeType { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> OrganisationDetailsId { get; set; }
        public Nullable<System.Guid> SiteDetailsId { get; set; }
        public Nullable<System.Guid> AssetDetailsId { get; set; }
        public Nullable<System.Guid> ComponentDetailsId { get; set; }
        public Nullable<System.Guid> LocationDetailsId { get; set; }
        public Nullable<System.Guid> PartDetailsId { get; set; }
        public Nullable<System.Guid> AssetFamilyId { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsProtectingLocation { get; set; }
        public Nullable<bool> IsProtectingEquipment { get; set; }
        public Nullable<bool> Location_IsProtectingEquipment { get; set; }
        public string ErpIdentifier { get; set; }
        public Nullable<int> Asset_IntendedMethodology { get; set; }
        public Nullable<int> Component_IntendedMethodology { get; set; }
        public Nullable<int> Location_IntendedMethodology { get; set; }
        public Nullable<int> Part_IntendedMethodology { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
        public Nullable<System.Guid> AuditEventItemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgTreeNodeModelRuns> OrgTreeNodeModelRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgTreeNodes> OrgTreeNodes1 { get; set; }
        public virtual OrgTreeNodes OrgTreeNodes2 { get; set; }
        public virtual ComponentDetails ComponentDetails { get; set; }
    }
}
