//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgTreeNodeModelRuns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgTreeNodeModelRuns()
        {
            this.OrgTreeNodeModelRunInputs = new HashSet<OrgTreeNodeModelRunInputs>();
            this.OrgTreeNodeModelRunOutputs = new HashSet<OrgTreeNodeModelRunOutputs>();
            this.InspectionPlans = new HashSet<InspectionPlans>();
            this.Recommendations = new HashSet<Recommendations>();
        }
    
        public System.Guid OrgTreeNodeModelRunId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public System.Guid ModelId { get; set; }
        public string Name { get; set; }
        public System.Guid OrgTreeNodeId { get; set; }
        public int ScenarioType { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public Nullable<System.Guid> MassCriticalityRunId { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgTreeNodeModelRunInputs> OrgTreeNodeModelRunInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgTreeNodeModelRunOutputs> OrgTreeNodeModelRunOutputs { get; set; }
        public virtual OrgTreeNodes OrgTreeNodes { get; set; }
        public virtual RunnableModel RunnableModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionPlans> InspectionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recommendations> Recommendations { get; set; }
    }
}
