//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T0NKME06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendations
    {
        public System.Guid RecommendationId { get; set; }
        public System.Guid OrgTreeNodeModelRunId { get; set; }
        public int RowIndex { get; set; }
        public string TaskExtent { get; set; }
        public float TaskFrequency { get; set; }
        public string TaskInterval { get; set; }
        public string TaskName { get; set; }
        public string TaskReference { get; set; }
        public string MitigationType { get; set; }
        public string DisplayedMitigationColumns { get; set; }
        public string MitigationSource { get; set; }
        public bool OverrideFrequency { get; set; }
        public bool LastInspectionDateOverriden { get; set; }
        public System.Guid MitigationRowId { get; set; }
        public System.Guid MasterInspectionMethodId { get; set; }
    
        public virtual OrgTreeNodeModelRuns OrgTreeNodeModelRuns { get; set; }
    }
}
